services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celsia-webapp
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"